apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: discovery-service
  template:
    metadata:
      labels:
        app: discovery-service
    spec:
      containers:
        - name: discovery-service
          image: discovery-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8084
          readinessProbe:
            httpGet:
              port: 8084
              path: /discovery/actuator/health/readiness
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              port: 8084
              path: /discovery/actuator/health/liveness
            initialDelaySeconds: 30
            periodSeconds: 10