apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: front-service
  template:
    metadata:
      labels:
        app: front-service
    spec:
      containers:
        - name: front-service
          image: front-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8086
          readinessProbe:
            httpGet:
              port: 8086
              path: /front/actuator/health/readiness
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              port: 8086
              path: /front/actuator/health/liveness
            initialDelaySeconds: 30
            periodSeconds: 10