apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  ports:
    - name: 80-8080
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: gateway-service
  type: LoadBalancer