apiVersion: apps/v1
kind: Deployment
metadata:
  name: part-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: part-service
  template:
    metadata:
      labels:
        app: part-service
    spec:
      containers:
        - name: part-service
          image: part-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          readinessProbe:
            httpGet:
              port: 8081
              path: /part/actuator/health/readiness
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              port: 8081
              path: /part/actuator/health/liveness
            initialDelaySeconds: 30
            periodSeconds: 10